### ISSUE TITLE
Solutions page: CTA section is not aligned and text is overlapping

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/ibm-dotcom-library-nextjs-test#41]
## Detailed description

Issue :- CTA Section is not aligned properly and the text is overlapping 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/43ee44bb-c5ef-4175-b5e3-d10ca158a3f2)

**Comment by RobertaJHahn** [comment]
Issue moved to [carbon-design-system/ibm-dotcom-library #3227](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3227) via [**ZenHub**](https://www.zenhub.com/)
